### ISSUE TITLE
version wrong

### ISSUE THREAD

**Issue by changzhenxuan** [realoriginal/blacklotus#1]
I ran "make", and got "bootlicker.x64.exe" successfully. But I can not run the .exe file in both win10 and win11, the system will prompt me that the version is wrong. Is there any people could helo me?
![屏幕截图(4)](https://github.com/realoriginal/blacklotus/assets/80043284/8fffc5a5-53d5-4bb1-a8e7-00fb75fc175a)

**Comment by realoriginal** [comment]
![image](https://github.com/realoriginal/blacklotus/assets/118862626/e664a277-f036-42d7-b1a0-c53a43ae0c47)

**Comment by changzhenxuan** [comment]
what role does the bootlicker.x64.exe play ?  I stuck here for a long time. o.O 5555
